# Change these first
owner: EliasMET # Your GitHub organization or username, where this repository lives
repo: sdhs-monitoring # The name of this repository

sites:
  - name: API Backend
    url: $API_BACKEND_URL
  - name: Roblox
    url: https://roblox.com
  - name: Bloxlink API
    url: https://api.blox.link/v4
  - name: Discord Bot
    url: $DISCORD_BOT_URL
  - name: Agent Discord Bot
    url: $AGENT_BOT_URL


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /sdhs-monitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SDHS-Monitoring


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
